services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        container_name: sports_laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
            - "6001:6001"  # за WebSocket
        networks:
            - sports_network
        depends_on:
            - db
            - rabbitmq
        entrypoint: [ "/usr/local/bin/docker-entrypoint.sh" ]
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: 123456
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: guest
            RABBITMQ_PASSWORD: guest

    db:
        image: mariadb:10.5
        container_name: sports_mariadb
        environment:
            MARIADB_DATABASE: laravel
            MARIADB_ROOT_PASSWORD: 123456
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - sports_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sports_phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - sports_network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: sports_rabbitmq
        ports:
            - "5672:5672"   # AMQP порт
            - "15672:15672" # Management UI порт
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - sports_network

networks:
    sports_network:
        name: sports_network
        driver: bridge

volumes:
    mysql_data:
        name: sports_mysql_data
    rabbitmq_data:
        name: sports_rabbitmq_data
